# Copyright (c) 2017 Aimirim STI.

endPoint: opc.tcp://192.168.100.100:4800

nodes:
  - nodeName: ns=1;s=Umid_PV
    metricName: Umid_PV
  - nodeName: ns=1;s=EN_MFAC
    metricName: EN_MFAC
  - nodeName: ns=1;s=RPM_MO
    metricName: RPM_MO