# Copyright (c) 2017 Aimirim STI.

global:
  scrape_interval:     20s
  evaluation_interval: 20s

scrape_configs:
  - job_name: Exporter
    static_configs:
      - targets: ['exporter:9686']
        labels:
          group: 'exporter'
